# Generated by Django 2.1.7 on 2019-04-21 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0002_auto_20190416_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='heroe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField()),
                ('rewards', models.TextField()),
                ('lived', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='heroes',
        ),
        migrations.RenameModel(
            old_name='events',
            new_name='event',
        ),
        migrations.AddField(
            model_name='heroe',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mains.event'),
        ),
    ]
