# Generated by Django 2.1.7 on 2019-04-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0003_auto_20190421_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroe',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
