# Generated by Django 2.1.7 on 2019-06-03 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0006_auto_20190603_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('place_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mains.event')),
            ],
        ),
        migrations.RenameField(
            model_name='heroe',
            old_name='participant',
            new_name='heroe_id',
        ),
    ]
