# Generated by Django 2.1.7 on 2019-06-03 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0007_auto_20190603_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('took_part_events', models.CharField(max_length=200)),
                ('comander', models.CharField(max_length=100)),
                ('army_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mains.event')),
            ],
        ),
    ]
