# Generated by Django 2.1.7 on 2019-06-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0009_auto_20190603_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='army',
            name='army_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
        migrations.AddField(
            model_name='heroe',
            name='took_part',
            field=models.ManyToManyField(to='mains.event'),
        ),
        migrations.RemoveField(
            model_name='army',
            name='took_part_events',
        ),
        migrations.AddField(
            model_name='army',
            name='took_part_events',
            field=models.ManyToManyField(to='mains.event'),
        ),
        migrations.AlterField(
            model_name='heroe',
            name='heroe_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mains.army'),
        ),
        migrations.DeleteModel(
            name='events_has_Army',
        ),
    ]
