# Generated by Django 2.1.7 on 2019-06-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0010_auto_20190603_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroe',
            name='heroe_id',
        ),
        migrations.RemoveField(
            model_name='heroe',
            name='took_part',
        ),
        migrations.AddField(
            model_name='army',
            name='heroes',
            field=models.ManyToManyField(to='mains.heroe'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(to='mains.heroe'),
        ),
    ]
