# Generated by Django 2.1.7 on 2019-06-03 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0011_auto_20190603_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='army',
            name='heroes',
        ),
        migrations.AddField(
            model_name='army',
            name='heroes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mains.heroe'),
        ),
    ]
