# Generated by Django 2.1.7 on 2019-06-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0012_auto_20190603_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='army',
            name='heroes',
        ),
        migrations.AddField(
            model_name='heroe',
            name='army',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mains.army'),
        ),
    ]
